sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.4"

before_install:
  - pip3 install cwltool
  - docker build -t snvly .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /snvly/.travis/unit-test.sh snvly
  # Unit tests
  - docker run --entrypoint /snvly/functional_tests/snvly-test.sh snvly -p snvly -d /snvly/functional_tests/test_data -v

  # CWL definition test
  - cwltool snvly.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
